"""Map Budion food-icon IDs to Material Design Icons."""

from __future__ import annotations

from .const import (
    SENSOR_MEAL_BREAKFAST,
    SENSOR_MEAL_DINNER,
    SENSOR_MEAL_LUNCH,
    SENSOR_MEAL_SNACK,
)

DEFAULT_FOOD_ICON_MDI = "mdi:silverware-fork-knife"

# Defaults when no per-entry icon is set.
MEAL_TYPE_ICONS: dict[str, str] = {
    SENSOR_MEAL_BREAKFAST: "mdi:food-croissant",
    SENSOR_MEAL_LUNCH: "mdi:sandwich",
    SENSOR_MEAL_DINNER: "mdi:silverware-fork-knife",
    SENSOR_MEAL_SNACK: "mdi:cookie",
}

# Budion food-icon ids (and legacy aliases) → mdi.
_FOOD_ICON_MDI: dict[str, str] = {
    # Meals / prepared food
    "pizza-slice": "mdi:pizza",
    "full-pizza": "mdi:pizza",
    "pizza": "mdi:pizza",
    "hamburger": "mdi:hamburger",
    "hot-dog": "mdi:food-hot-dog",
    "taco": "mdi:taco",
    "doner-kebab": "mdi:food-kebab",
    "kebab-spit": "mdi:food-kebab",
    "kebab": "mdi:food-kebab",
    "sandwich": "mdi:sandwich",
    "french-fries": "mdi:french-fries",
    "nachos": "mdi:nachos",
    "pretzel": "mdi:pretzel",
    "bread": "mdi:bread-slice",
    "bread-slice": "mdi:bread-slice",
    "butter-toast": "mdi:toaster-oven",
    "croissant": "mdi:food-croissant",
    "sushi": "mdi:food-sushi",
    "dumpling": "mdi:food-takeout-box",
    "dumpling-bao": "mdi:food-takeout-box",
    "noodles": "mdi:noodles",
    "fast-noodles": "mdi:noodles",
    "noodle-ball": "mdi:noodles",
    "rice-bowl": "mdi:rice",
    "rice-cooker": "mdi:rice",
    "wok": "mdi:bowl-mix",
    "cooking-pot": "mdi:pot-steam",
    "saucepan": "mdi:pot-mix",
    "hot-meal": "mdi:food",
    "meal": "mdi:food",
    "soup": "mdi:pot-steam",
    "fork-knife-spoon": "mdi:silverware-fork-knife",
    "knife-fork": "mdi:silverware-fork-knife",
    "utensils": "mdi:silverware-fork-knife",
    "utensils-crossed": "mdi:silverware-fork-knife",
    "chopsticks": "mdi:chopsticks",
    "chef-hat": "mdi:chef-hat",
    "cooking-glove": "mdi:oven",
    "barbecue": "mdi:grill",
    "food-truck": "mdi:truck",
    "camp-cooking": "mdi:campfire",
    "pressure-cooker": "mdi:pot-steam",
    "cook": "mdi:chef-hat",
    # Meat / fish
    "steak": "mdi:food-steak",
    "beef": "mdi:food-steak",
    "meat": "mdi:food-steak",
    "bacon": "mdi:food-steak",
    "ham": "mdi:food-steak",
    "sausage": "mdi:sausage",
    "charcuterie": "mdi:food-steak",
    "roast-chicken": "mdi:food-drumstick",
    "chicken-leg": "mdi:food-drumstick",
    "chicken": "mdi:food-drumstick",
    "drumstick": "mdi:food-drumstick",
    "turkey": "mdi:food-turkey",
    "fish-cooked": "mdi:fish",
    "fried-fish": "mdi:fish",
    "salmon": "mdi:fish",
    "fish": "mdi:fish",
    "fish-symbol": "mdi:fish",
    "shrimp": "mdi:shrimp",
    "crab": "mdi:crab",
    "octopus": "mdi:octopus",
    "squid": "mdi:jellyfish",
    "mussel": "mdi:snail",
    "oyster": "mdi:snail",
    "scallop": "mdi:snail",
    "canned-fish": "mdi:fish",
    "sheep": "mdi:sheep",
    # Fruit / veg
    "shiny-apple": "mdi:food-apple",
    "apple-core": "mdi:food-apple",
    "apple": "mdi:food-apple",
    "banana": "mdi:food-apple",
    "banana-bunch": "mdi:food-apple",
    "orange": "mdi:fruit-citrus",
    "orange-slice": "mdi:fruit-citrus",
    "citrus": "mdi:fruit-citrus",
    "lemon": "mdi:fruit-citrus",
    "cut-lemon": "mdi:fruit-citrus",
    "strawberry": "mdi:fruit-grapes",
    "cherry": "mdi:fruit-cherries",
    "grapes": "mdi:fruit-grapes",
    "grape": "mdi:fruit-grapes",
    "watermelon": "mdi:fruit-watermelon",
    "pineapple": "mdi:fruit-pineapple",
    "peach": "mdi:fruit-cherries",
    "pear": "mdi:fruit-pear",
    "raspberry": "mdi:fruit-grapes",
    "tangerine": "mdi:fruit-citrus",
    "kiwi": "mdi:fruit-citrus",
    "avocado": "mdi:fruit-pear",
    "coconut": "mdi:circle-outline",
    "fruit-bowl": "mdi:bowl",
    "berries-bowl": "mdi:bowl",
    "berry-bush": "mdi:fruit-grapes",
    "salad": "mdi:bowl-mix",
    "carrot": "mdi:carrot",
    "broccoli": "mdi:broccoli",
    "leafy-green": "mdi:leaf",
    "cabbage": "mdi:cabbage",
    "tomato": "mdi:food-apple",
    "bell-pepper": "mdi:pepper",
    "chili-pepper": "mdi:chili-hot",
    "aubergine": "mdi:eggplant",
    "asparagus": "mdi:food",
    "beet": "mdi:food",
    "leek": "mdi:food",
    "garlic": "mdi:garlic",
    "mushroom": "mdi:mushroom",
    "mushrooms": "mdi:mushroom",
    "potato": "mdi:potato",
    "pumpkin": "mdi:pumpkin",
    "corn": "mdi:corn",
    "peas": "mdi:peanut",
    "bean": "mdi:peanut",
    "vegan": "mdi:leaf",
    "olive": "mdi:circle",
    "peanut": "mdi:peanut",
    "nut": "mdi:peanut",
    "almond": "mdi:peanut",
    "sesame": "mdi:circle-small",
    "wheat": "mdi:barley",
    "sugar-cane": "mdi:cane",
    # Dairy / eggs
    "cheese": "mdi:cheese",
    "milk": "mdi:cow",
    "fried-eggs": "mdi:egg-fried",
    "raw-egg": "mdi:egg",
    "egg": "mdi:egg",
    "egg-fried": "mdi:egg-fried",
    "butter": "mdi:butter",
    # Sweets / snacks
    "cake-slice": "mdi:cake-variant",
    "cake": "mdi:cake-variant",
    "cupcake": "mdi:cupcake",
    "donut": "mdi:donut",
    "cookie": "mdi:cookie",
    "chocolate": "mdi:candy",
    "candy-canes": "mdi:candy",
    "candy-cane": "mdi:candy",
    "candy": "mdi:candy",
    "wrapped-sweet": "mdi:candy",
    "ice-cream-cone": "mdi:ice-cream",
    "ice-cream-scoop": "mdi:ice-cream",
    "ice-pop": "mdi:ice-cream",
    "popsicle": "mdi:ice-cream",
    "jelly": "mdi:cup",
    "jelly-beans": "mdi:candy",
    "marshmallows": "mdi:candy",
    "honey-jar": "mdi:bee",
    "honeycomb": "mdi:bee",
    "pie-slice": "mdi:cake-variant",
    "popcorn": "mdi:popcorn",
    "gingerbread": "mdi:cookie",
    "chips-bag": "mdi:baguette",
    # Drinks
    "coffee-cup": "mdi:coffee",
    "coffee-mug": "mdi:coffee",
    "coffee-beans": "mdi:coffee",
    "coffee": "mdi:coffee",
    "moka-pot": "mdi:coffee-maker",
    "teapot": "mdi:tea",
    "beer-bottle": "mdi:beer",
    "beer-stein": "mdi:beer",
    "beer": "mdi:beer",
    "wine-glass": "mdi:glass-wine",
    "wine-bottle": "mdi:bottle-wine",
    "bottle-wine": "mdi:bottle-wine",
    "wine": "mdi:glass-wine",
    "brandy": "mdi:glass-flute",
    "martini": "mdi:glass-cocktail",
    "soda-can": "mdi:bottle-soda",
    "cup-soda": "mdi:bottle-soda",
    "water-bottle": "mdi:water",
    "manual-juicer": "mdi:cup",
    # Pantry / misc
    "cool-spices": "mdi:shaker",
    "hot-spices": "mdi:chili-hot",
    "ketchup": "mdi:bottle-tonic",
    "salt": "mdi:shaker-outline",
    "flour": "mdi:baguette",
    "pickle": "mdi:food",
    "food-can": "mdi:food",
    "pestle-mortar": "mdi:mortar-pestle",
    "toaster": "mdi:toaster",
    "cornucopia": "mdi:corn",
    "maple-leaf": "mdi:leaf-maple",
}


def resolve_food_icon_id(value: str | None) -> str | None:
    """Normalize a Budion food-icon id (including legacy aliases)."""
    if not value:
        return None
    icon_id = value.strip().lower()
    if not icon_id:
        return None
    return icon_id


def food_icon_to_mdi(value: str | None) -> str | None:
    """Return an mdi icon for a Budion food-icon id, if known."""
    icon_id = resolve_food_icon_id(value)
    if icon_id is None:
        return None
    return _FOOD_ICON_MDI.get(icon_id)
